### ISSUE TITLE
Plugin Build

### ISSUE THREAD

**Issue by momoeziku** [Deccentric/WhatchaSay#3]
Hi, do I have to build first to get it work, or just need to add your custom repo inside Dalamud and run the plugin from there?

**Comment by Deccentric** [comment]
Nope, building is totally optional, I just added those instructions for if anyone DID want to build it. You should just have to add the repo inside Dalamud and it should be good to go. 😄 

Let me know if you run into any problems.

**Comment by momoeziku** [comment]
Yes, sorry to disturb again, but when I installed the plugin, it seems didnt work. I set basic option to Enabled, Translate Self on, but the translation just wont come up. If I tried via the translate box, even 1 word like "bread" in JPN take around 1 min to translate to ENG. I use LibreTranslate since DeepL unable to detect my country region for the credit info signup.

**Comment by Deccentric** [comment]
I currently am working on a way to use DeepL without the need of an API Key, so you will no longer have to make an account once I add that.

For the delay you're seeing though, I'd recommend to attempt to switch the LibreTranslate host in the /whatchasay menu. These are all hosted by people I believe are in the US, but I've found some work better than others. The people I know in NA that have used it get their translations < 1 second, but the performance of each server seems to fluctuate.

The default host, argosopentech, seems to be having some performance issues in my personal experience this past week.
