### ISSUE TITLE
hope to add target language Simplified Chinese or Traditional Chinese

### ISSUE THREAD

**Issue by trulynb** [Deccentric/WhatchaSay#6]
hope to add target language——Simplified Chinese or Traditional Chinese，thanks

**Comment by Deccentric** [comment]
![image psd](https://github.com/Deccentric/WhatchaSay/assets/147668414/c296e856-3891-4382-bd77-b3d2cbf1974f)
It appears the character set is not supported unfortunately. 

I don't know anything about Chinese though, so if you have any ideas please let me know.

😢

**Comment by trulynb** [comment]
According to your picture, the Chinese language is already supported, but because of your font, the Chinese characters are not fully displayed . In fact, you only need to add Chinese characters to the target language. How to use it depends on  user.

**Comment by trulynb** [comment]
For example, I've patched the Chinese fonts myself, so as long as you add Chinese to the target language, the Chinese translations I have here will be displayed properly.

**Comment by Deccentric** [comment]
Sure, I'll push what I have.

**Comment by Deccentric** [comment]
[Changes are live](https://github.com/Deccentric/WhatchaSay/commit/ff2c8eb2d540f6b86a6a0db21806fbb216c2ef24)
